apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: sezayir/myspringboot-image:v1
        ports:
        - containerPort: 8081
---        
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8081
  type: LoadBalancer